#!/bin/sh
docker push setsoft/kicad_debian:11.5-5.1.9
docker push setsoft/kicad_debian:ki6.0.9_Debian
docker push setsoft/kicad_auto:11.5-5.1.9
docker push setsoft/kicad_auto:ki6.0.9_Debian
docker push setsoft/kicad_auto_test:11.5-5.1.9
docker push setsoft/kicad_auto_test:ki6.0.9_Debian
docker push ghcr.io/inti-cmnb/kicad_debian:11.5-5.1.9
docker push ghcr.io/inti-cmnb/kicad_debian:ki6.0.9_Debian
docker push ghcr.io/inti-cmnb/kicad_auto:11.5-5.1.9
docker push ghcr.io/inti-cmnb/kicad_auto:ki6.0.9_Debian
docker push ghcr.io/inti-cmnb/kicad_auto_test:11.5-5.1.9
docker push ghcr.io/inti-cmnb/kicad_auto_test:ki6.0.9_Debian
docker push ghcr.io/inti-cmnb/kicad_debian:latest
docker push ghcr.io/inti-cmnb/kicad_debian:ki6
docker push ghcr.io/inti-cmnb/kicad5_debian:latest
docker push ghcr.io/inti-cmnb/kicad5_debian:5.1.9
docker push ghcr.io/inti-cmnb/kicad5_debian:5.1.9_d11.5
docker push ghcr.io/inti-cmnb/kicad6_debian:latest
docker push ghcr.io/inti-cmnb/kicad6_debian:6.0.9
docker push ghcr.io/inti-cmnb/kicad6_debian:6.0.9_d11.5
docker push ghcr.io/inti-cmnb/kicad_auto:latest
docker push ghcr.io/inti-cmnb/kicad_auto:ki6
docker push ghcr.io/inti-cmnb/kicad5_auto:latest
docker push ghcr.io/inti-cmnb/kicad5_auto:1.4.0
docker push ghcr.io/inti-cmnb/kicad5_auto:1.4.0-5_k5.1.9_d11.5
docker push ghcr.io/inti-cmnb/kicad6_auto:latest
docker push ghcr.io/inti-cmnb/kicad6_auto:1.4.0
docker push ghcr.io/inti-cmnb/kicad6_auto:1.4.0-5_k6.0.9_d11.5
docker push ghcr.io/inti-cmnb/kicad_auto_test:latest
docker push ghcr.io/inti-cmnb/kicad_auto_test:ki6
docker push ghcr.io/inti-cmnb/kicad5_auto_full:latest
docker push ghcr.io/inti-cmnb/kicad5_auto_full:1.4.0
docker push ghcr.io/inti-cmnb/kicad5_auto_full:1.4.0-5_k5.1.9_d11.5
docker push ghcr.io/inti-cmnb/kicad6_auto_full:latest
docker push ghcr.io/inti-cmnb/kicad6_auto_full:1.4.0
docker push ghcr.io/inti-cmnb/kicad6_auto_full:1.4.0-5_k6.0.9_d11.5
