#!/bin/sh
docker push setsoft/kicad_debian:11.6-5.1.9
docker push setsoft/kicad_debian:ki6.0.10_Debian
docker push setsoft/kicad_auto:11.6-5.1.9
docker push setsoft/kicad_auto:ki6.0.10_Debian
docker push setsoft/kicad_auto_test:11.6-5.1.9
docker push setsoft/kicad_auto_test:ki6.0.10_Debian
docker push ghcr.io/inti-cmnb/kicad_debian:11.6-5.1.9
docker push ghcr.io/inti-cmnb/kicad_debian:ki6.0.10_Debian
docker push ghcr.io/inti-cmnb/kicad_auto:11.6-5.1.9
docker push ghcr.io/inti-cmnb/kicad_auto:ki6.0.10_Debian
docker push ghcr.io/inti-cmnb/kicad_auto_test:11.6-5.1.9
docker push ghcr.io/inti-cmnb/kicad_auto_test:ki6.0.10_Debian
docker push ghcr.io/inti-cmnb/kicad_debian:latest
docker push ghcr.io/inti-cmnb/kicad_debian:ki6
docker push ghcr.io/inti-cmnb/kicad5_debian:latest
docker push ghcr.io/inti-cmnb/kicad5_debian:5.1.9
docker push ghcr.io/inti-cmnb/kicad5_debian:5.1.9_d11.6
docker push ghcr.io/inti-cmnb/kicad6_debian:latest
docker push ghcr.io/inti-cmnb/kicad6_debian:6.0.10
docker push ghcr.io/inti-cmnb/kicad6_debian:6.0.10_d11.6
docker push ghcr.io/inti-cmnb/kicad_auto:latest
docker push ghcr.io/inti-cmnb/kicad_auto:ki6
docker push ghcr.io/inti-cmnb/kicad5_auto:latest
docker push ghcr.io/inti-cmnb/kicad5_auto:1.6.0
docker push ghcr.io/inti-cmnb/kicad5_auto:1.6.0-1_k5.1.9_d11.6
docker push ghcr.io/inti-cmnb/kicad6_auto:latest
docker push ghcr.io/inti-cmnb/kicad6_auto:1.6.0
docker push ghcr.io/inti-cmnb/kicad6_auto:1.6.0-1_k6.0.10_d11.6
docker push ghcr.io/inti-cmnb/kicad_auto_test:latest
docker push ghcr.io/inti-cmnb/kicad_auto_test:ki6
docker push ghcr.io/inti-cmnb/kicad5_auto_full:latest
docker push ghcr.io/inti-cmnb/kicad5_auto_full:1.6.0
docker push ghcr.io/inti-cmnb/kicad5_auto_full:1.6.0-1_k5.1.9_d11.6
docker push ghcr.io/inti-cmnb/kicad6_auto_full:latest
docker push ghcr.io/inti-cmnb/kicad6_auto_full:1.6.0
docker push ghcr.io/inti-cmnb/kicad6_auto_full:1.6.0-1_k6.0.10_d11.6
