# Fixes the --use-board-stackup-colors option for kicad-cli pcb render
# This option defaults to true making impossible to be disabled.
# So the --preset option becomes useless, no layer or colors selection.
# https://gitlab.com/kicad/code/kicad/-/work_items/21950
#
# Vibe coded by Salvador E. Tropea
# Code generated by Gemini 3.1 Pro (Preview)
import os
import sys

try:
    import lief
    from capstone import *
    from capstone.x86 import *
except ImportError:
    print("Please install dependencies first: pip install lief capstone")
    sys.exit(1)

def get_arch_mode(binary):
    # Safely determine architecture without relying on removed LIEF enums
    try:
        if isinstance(binary, lief.ELF.Binary):
            if "i386" in str(binary.header.machine_type).lower():
                return CS_ARCH_X86, CS_MODE_32
        elif hasattr(lief, 'PE') and isinstance(binary, lief.PE.Binary):
            if "i386" in str(binary.header.machine).lower():
                return CS_ARCH_X86, CS_MODE_32
    except Exception:
        pass
    return CS_ARCH_X86, CS_MODE_64 # Default fallback to x86_64

def auto_patch(binary_path):
    print(f"[*] Parsing binary: {binary_path}")
    binary = lief.parse(binary_path)
    if not binary:
        print("[-] Failed to parse binary.")
        return

    arch, mode = get_arch_mode(binary)
    target_string = b"--use-board-stackup-colors"
    string_va = None
    
    # 1. Locate the string in the read-only data sections
    for section in binary.sections:
        content = bytes(section.content)
        idx = content.find(target_string)
        if idx != -1:
            string_va = section.virtual_address + idx
            print(f"[+] Found string '{target_string.decode()}' at VA: {hex(string_va)}")
            break

    if not string_va:
        print("[-] The string was not found in the binary.")
        return

    text_section = binary.get_section(".text")
    if not text_section:
        print("[-] .text section not found.")
        return

    print("[*] Scanning .text section for references (fast scanning)...")
    text_content = bytes(text_section.content)
    text_va = text_section.virtual_address
    
    # Fast byte scan for RIP-relative offsets (PIE)
    # offset32 = target_va - (instruction_va + 4)
    # Thus: offset32 + index = target_va - text_va - 4
    C = string_va - text_va - 4
    candidates = []
    
    limit = len(text_content) - 4
    for i in range(limit):
        # Fast pre-check of the least significant byte to avoid overhead
        if text_content[i] == ((C - i) & 0xFF):
            val = int.from_bytes(text_content[i:i+4], 'little', signed=True)
            if val == C - i:
                candidates.append(text_va + i)

    if not candidates:
        print("[-] No relative reference found via fast-scan. Falling back to full disassembly...")
        md = Cs(arch, mode)
        md.detail = True
        md.skipdata = True
        
        for inst in md.disasm(text_content, text_va):
            for op in inst.operands:
                target = None
                if op.type == X86_OP_MEM and op.mem.base == X86_REG_RIP:
                    target = inst.address + inst.size + op.mem.disp
                elif op.type == X86_OP_IMM:
                    target = op.imm
                    
                if target == string_va:
                    candidates.append(inst.address)
                    break
            if candidates:
                break

    if not candidates:
        print("[-] Could not find any code referencing the string.")
        return

    print(f"[+] Code pointing to string found near VA: {[hex(c) for c in candidates]}")
    
    md = Cs(arch, mode)
    md.detail = True
    
    patch_inst = None
    string_patch_inst = None
    
    # 2. Disassemble a tiny window around the candidate to find the `true` (1) bool
    for cand_va in candidates:
        # Start a bit before the displacement to capture the whole instruction
        start_va = max(text_va, cand_va - 15)
        offset = start_va - text_va
        window = text_content[offset:offset+400]
        
        instructions = list(md.disasm(window, start_va))
        
        xref_idx = -1
        for i, inst in enumerate(instructions):
            for op in inst.operands:
                target = None
                if op.type == X86_OP_MEM and op.mem.base == X86_REG_RIP:
                    target = inst.address + inst.size + op.mem.disp
                elif op.type == X86_OP_IMM:
                    target = op.imm
                
                if target == string_va:
                    print(f"[+] Confirmed code reference at {hex(inst.address)}: {inst.mnemonic} {inst.op_str}")
                    xref_idx = i
                    break
            if xref_idx != -1:
                break
                
        if xref_idx != -1:
            # 3. Scan up to 60 instructions ahead for the boolean 'true' (1) parameter
            print("[*] Scanning ahead for the boolean argument ('true' / 1)...")
            for i in range(xref_idx, min(xref_idx + 60, len(instructions))):
                inst = instructions[i]
                
                if inst.id in (X86_INS_MOV, X86_INS_PUSH):
                    op_idx = 1 if inst.id == X86_INS_MOV else 0
                    if len(inst.operands) > op_idx and inst.operands[op_idx].type == X86_OP_IMM:
                        # Found the boolean `true` (1)
                        if inst.operands[op_idx].imm == 1 and not patch_inst:
                            patch_inst = inst
                            print(f"[+] Found boolean 'true' argument at {hex(inst.address)}: {inst.mnemonic} {inst.op_str}")
                        
                        # Check for the inlined string "true" (0x65757274) injected by argparse for the help menu
                        if inst.operands[op_idx].imm == 0x65757274 and not string_patch_inst:
                            string_patch_inst = inst
                            print(f"[+] Found SSO help string 'true' at {hex(inst.address)}: {inst.mnemonic} {inst.op_str}")
            
            if patch_inst:
                break 

    if not patch_inst:
        print("[-] Could not locate instruction passing '1'.")
        return

    # 4. Apply Patches
    with open(binary_path, "rb") as f:
        data = bytearray(f.read())

    # Patch 1: The logic boolean
    file_offset = binary.virtual_address_to_offset(patch_inst.address)
    inst_bytes = bytearray(patch_inst.bytes)
    
    patch_offset_in_inst = -1
    if inst_bytes[-1] == 1:
        patch_offset_in_inst = len(inst_bytes) - 1
    elif len(inst_bytes) >= 4 and inst_bytes[-4] == 1 and inst_bytes[-3:] == b'\x00\x00\x00':
        patch_offset_in_inst = len(inst_bytes) - 4
    else:
        try: patch_offset_in_inst = inst_bytes.index(1)
        except ValueError: pass

    if patch_offset_in_inst == -1:
        print("[-] Failed to find the 0x01 byte inside the instruction.")
        return

    final_file_offset = file_offset + patch_offset_in_inst
    print(f"[+] Will patch logic (1 -> 0) at file offset: {hex(final_file_offset)}")
    data[final_file_offset] = 0x00

    # Patch 2 (Optional): The [default: true] help text label
    if string_patch_inst:
        s_file_offset = binary.virtual_address_to_offset(string_patch_inst.address)
        s_inst_bytes = bytearray(string_patch_inst.bytes)
        idx = s_inst_bytes.find(b'\x74\x72\x75\x65') # 't', 'r', 'u', 'e'
        if idx != -1:
            final_s_offset = s_file_offset + idx
            data[final_s_offset:final_s_offset+4] = b'\x66\x61\x6c\x73' # 'f', 'a', 'l', 's'
            print(f"[+] Will patch help text ('true' -> 'fals') at file offset: {hex(final_s_offset)}")

    print("")
#     ans = input("Apply these patches? (y/n): ")
#     if ans.lower() != 'y':
#         print("Aborted.")
#         return

#     backup = binary_path + ".bak"
#     with open(backup, "wb") as f:
#         with open(binary_path, "rb") as orig:
#             f.write(orig.read())
            
#     patched_path = binary_path + ".patched"
#     with open(patched_path, "wb") as f:
#         f.write(data)

    patched_path = binary_path
    with open(patched_path, "wb") as f:
        f.write(data)
        
    if os.name == 'posix':
        os.chmod(patched_path, 0o755)
        
    print(f"[+] Successfully patched! Output saved to: {patched_path}")

if __name__ == "__main__":
    print("`kicad-cli pcb render --use-board-stackup-colors` fixer")
    if len(sys.argv) < 2:
        print("Usage: python3 patch_cli.py <binary_file>")
        sys.exit(1)
    auto_patch(sys.argv[1])
